import { Employee, Task, TaskAssignment, AuditLog } from './types';

export const mockEmployees: Employee[] = [
  {
    id: 1,
    first_name: 'Sarah',
    last_name: 'Johnson',
    email: 'sarah.johnson@company.com',
    department: 'Engineering',
    position: 'Senior Software Engineer',
    manager_id: null,
    role_type: 'Custom',
    onboarding_status: 'in_progress',
    start_date: new Date().toISOString().split('T')[0],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    first_name: 'Michael',
    last_name: 'Chen',
    email: 'michael.chen@company.com',
    department: 'Marketing',
    position: 'Marketing Manager',
    manager_id: 1,
    role_type: 'Custom',
    onboarding_status: 'not_started',
    start_date: new Date().toISOString().split('T')[0],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    first_name: 'Emily',
    last_name: 'Rodriguez',
    email: 'emily.rodriguez@company.com',
    department: 'HR',
    position: 'HR Specialist',
    manager_id: null,
    role_type: 'Custom',
    onboarding_status: 'completed',
    start_date: '2024-01-15',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockTasks: Task[] = [
  {
    id: 1,
    employee_id: 1,
    task_type: 'IT_SETUP',
    title: 'Set up laptop and email account',
    description: 'Provision company laptop, email, and essential software',
    priority: 'HIGH',
    status: 'completed',
    due_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    generated_by_agent: 'TASK_AGENT',
    agent_reasoning: 'Standard IT setup for new employees',
  },
  {
    id: 2,
    employee_id: 1,
    task_type: 'HR_PAPERWORK',
    title: 'Complete employment contract',
    description: 'Review and sign employment contract and related documents',
    priority: 'HIGH',
    status: 'in_progress',
    due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    generated_by_agent: 'TASK_AGENT',
    agent_reasoning: 'Critical HR documentation required',
  },
  {
    id: 3,
    employee_id: 1,
    task_type: 'TRAINING',
    title: 'Complete company onboarding module',
    description: 'Complete online onboarding course and policy training',
    priority: 'MEDIUM',
    status: 'pending',
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    generated_by_agent: 'TASK_AGENT',
    agent_reasoning: 'Mandatory onboarding training',
  },
  {
    id: 4,
    employee_id: 2,
    task_type: 'IT_SETUP',
    title: 'Configure VPN and network access',
    description: 'Set up VPN credentials and ensure network connectivity',
    priority: 'HIGH',
    status: 'pending',
    due_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    generated_by_agent: 'TASK_AGENT',
    agent_reasoning: 'Network access essential for day one',
  },
];

export const mockAssignments: TaskAssignment[] = [
  {
    id: 1,
    task_id: 1,
    assigned_to: 2,
    assigned_by: 3,
    assignment_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    start_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    completion_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
    is_delayed: false,
    delay_escalated: false,
    notes: 'Successfully completed',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    task_id: 2,
    assigned_to: 3,
    assigned_by: 1,
    assignment_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    start_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'in_progress',
    is_delayed: false,
    delay_escalated: false,
    notes: 'In progress, on schedule',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    task_id: 3,
    assigned_to: 2,
    assigned_by: 1,
    assignment_date: new Date().toISOString(),
    status: 'assigned',
    is_delayed: false,
    delay_escalated: false,
    notes: 'Pending start',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 1,
    agent_name: 'TaskAgent',
    agent_type: 'TASK_AGENT',
    action_type: 'GENERATE_TASKS',
    description: 'Generated 11 onboarding tasks for new employee Sarah Johnson',
    reasoning: 'Task Agent analyzed employee profile (Senior Software Engineer) and generated comprehensive onboarding task list covering IT setup, HR paperwork, training, and department orientation.',
    parameters: { employee_id: 1, task_count: 11 },
    result_status: 'success',
    task_id: 1,
    employee_id: 1,
    groq_response: { tasks_generated: 11, categories: ['IT', 'HR', 'Training', 'Department'] },
    groq_model: 'mixtral-8x7b-32768',
    groq_prompt_tokens: 245,
    groq_completion_tokens: 512,
    execution_time_ms: 1240,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    agent_name: 'ExecutionAgent',
    agent_type: 'EXECUTION_AGENT',
    action_type: 'ASSIGN_TASK',
    description: 'Assigned task "Set up laptop and email account" to Michael Chen',
    reasoning: 'Execution Agent matched IT setup task with Michael Chen based on his IT team membership and current workload capacity.',
    parameters: { task_id: 1, assigned_to_id: 2 },
    result_status: 'success',
    task_id: 1,
    assignment_id: 1,
    groq_response: { assigned_to: 2, confidence: 0.92 },
    groq_model: 'mixtral-8x7b-32768',
    groq_prompt_tokens: 156,
    groq_completion_tokens: 289,
    execution_time_ms: 892,
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    agent_name: 'MonitoringAgent',
    agent_type: 'MONITORING_AGENT',
    action_type: 'DETECT_DELAY',
    description: 'No delays detected. All tasks on schedule.',
    reasoning: 'Monitoring Agent checked 15 active tasks. Average completion rate is 87%. No tasks exceed the 24-hour delay threshold.',
    parameters: { check_time: new Date().toISOString(), task_threshold: 24 },
    result_status: 'success',
    groq_response: { delayed_tasks: 0, at_risk_tasks: 2, on_schedule: 13 },
    groq_model: 'mixtral-8x7b-32768',
    groq_prompt_tokens: 189,
    groq_completion_tokens: 156,
    execution_time_ms: 756,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    agent_name: 'DecisionAgent',
    agent_type: 'DECISION_AGENT',
    action_type: 'ESCALATE_TASK',
    description: 'Escalated delayed task to department manager due to 26-hour overdue status',
    reasoning: 'Decision Agent detected task exceeded 24-hour threshold. Task critical for onboarding. Escalated to manager with recommendation for immediate attention.',
    parameters: { task_id: 4, escalation_level: 'manager', hours_overdue: 26 },
    result_status: 'success',
    task_id: 4,
    assignment_id: 3,
    groq_response: { action: 'escalate', escalation_level: 'manager', reason: 'critical_delay' },
    groq_model: 'mixtral-8x7b-32768',
    groq_prompt_tokens: 267,
    groq_completion_tokens: 198,
    execution_time_ms: 1015,
    created_at: new Date().toISOString(),
  },
];
